[project]
name = "renamer"
version = "1.0.0"
description = "PDF Renamer using LLM"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.1.1",
    "loguru>=0.7.2",
    "pymupdf>=1.24.14",
    "transformers>=4.46.3",
    "typer>=0.13.1",
]
